export enum EventTypes {
  Conferencia       = 'Conferencia',
  Congreso          = 'Congreso',
  Convocatoria      = 'Convocatoria',
  Foro              = 'Foro',
  Mock              = 'Mock',
  NetworkingSession = 'Networking session',
  Panel             = 'Panel',
  SemanaDeLaCarrera = 'Semana de la carrera',
  Seminario         = 'Seminario',
  Simposio          = 'Simposio',
  StudyJAM          = 'Study JAM',
  Takeover          = 'Takeover',
  Taller            = 'Taller',
  VisitaAEmpresa    = 'Visita a empresa',
  Otro              = 'Otro',
}

export const EventTypesArray = [
  'Conferencia',
  'Congreso',
  'Convocatoria',
  'Foro',
  'Mock',
  'Networking session',
  'Panel',
  'Semana de la carrera',
  'Seminario',
  'Simposio',
  'Study JAM',
  'Takeover',
  'Taller',
  'Visita a empresa',
  'Otro',
]
