import { Models } from '../enums/major-models.enum';

export interface Major {
  mid: string;
  model: Models;
  area: string;
  name: string;
}

export const majorsList: {
  Tec20: {[mid: string]: Major},
  Tec21: {[mid: string]: Major},
} = {
  Tec20: {
    'ADI': {mid: 'ADI', model: Models.Tec20, area: 'ADI', name: 'Arquitectura y Diseño / Exploración'},
    'ARQ': {mid: 'ARQ', model: Models.Tec20, area: 'ADI', name: 'Arquitecto'},
    'BIO': {mid: 'BIO', model: Models.Tec20, area: 'BIO', name: 'Bioingeniería y Procesos Químicos / Exploración'},
    'CIS': {mid: 'CIS', model: Models.Tec20, area: 'CIS', name: 'Ciencias Sociales y Gobierno / Exploración'},
    'COM': {mid: 'COM', model: Models.Tec20, area: 'COM', name: 'Comunicación y Producción Digital / Exploración'},
    'IA ': {mid: 'IA ', model: Models.Tec20, area: 'BIO', name: 'Ing. Agrónomo'},
    'IBN': {mid: 'IBN', model: Models.Tec20, area: 'BIO', name: 'Ing. en Bionegocios'},
    'IBT': {mid: 'IBT', model: Models.Tec20, area: 'BIO', name: 'Ing. en Biotecnología'},
    'IC ': {mid: 'IC ', model: Models.Tec20, area: 'ING', name: 'Ing. Civil'},
    'IDA': {mid: 'IDA', model: Models.Tec20, area: 'ING', name: 'Ing. en Diseño Automotriz'},
    'IDS': {mid: 'IDS', model: Models.Tec20, area: 'BIO', name: 'Ing. en Desarrollo Sustentable'},
    'IFI': {mid: 'IFI', model: Models.Tec20, area: 'ING', name: 'Ing. Física Industrial'},
    'IIA': {mid: 'IIA', model: Models.Tec20, area: 'BIO', name: 'Ing. en Industrias Alimentarias'},
    'IID': {mid: 'IID', model: Models.Tec20, area: 'ING', name: 'Ing. en Innovación y Desarrollo'},
    'IIS': {mid: 'IIS', model: Models.Tec20, area: 'ING', name: 'Ing. Industrial y de Sistemas'},
    'IMA': {mid: 'IMA', model: Models.Tec20, area: 'ING', name: 'Ing. Mecánico Administrador'},
    'IMD': {mid: 'IMD', model: Models.Tec20, area: 'BIO', name: 'Ing. Biomédico'},
    'IME': {mid: 'IME', model: Models.Tec20, area: 'ING', name: 'Ing. Mecánico Electricista'},
    'IMI': {mid: 'IMI', model: Models.Tec20, area: 'ING', name: 'Ing. en Producción Musical Digital'},
    'IMT': {mid: 'IMT', model: Models.Tec20, area: 'ING', name: 'Ing. en Mecatrónica'},
    'INC': {mid: 'INC', model: Models.Tec20, area: 'BIO', name: 'Ing. en Nanotecnología y Ciencias Químicas'},
    'ING': {mid: 'ING', model: Models.Tec20, area: 'ING', name: 'Ingeniería / Exploración'},
    'INT': {mid: 'INT', model: Models.Tec20, area: 'TIE', name: 'Ing. en Negocios y Tecnologías de Información'},
    'IQA': {mid: 'IQA', model: Models.Tec20, area: 'BIO', name: 'Ing. Químico Administrador'},
    'IQP': {mid: 'IQP', model: Models.Tec20, area: 'BIO', name: 'Ing. Químico en Procesos Sustentables'},
    'ISC': {mid: 'ISC', model: Models.Tec20, area: 'TIE', name: 'Ing. en Sistemas Computacionales'},
    'ISD': {mid: 'ISD', model: Models.Tec20, area: 'TIE', name: 'Ing. en Sistemas Digitales y Robótica'},
    'ITC': {mid: 'ITC', model: Models.Tec20, area: 'TIE', name: 'Ing. en Tecnologías Computacionales'},
    'ITE': {mid: 'ITE', model: Models.Tec20, area: 'TIE', name: 'Ing. en Tecnologías Electrónicas'},
    'ITI': {mid: 'ITI', model: Models.Tec20, area: 'TIE', name: 'Ing. en Tecnologías de Información'},
    'ITS': {mid: 'ITS', model: Models.Tec20, area: 'TIE', name: 'Ing. en Telecomunicaciónes y Sistemas Electrónicos'},
    'LAD': {mid: 'LAD', model: Models.Tec20, area: 'ADI', name: 'Lic. en Animación y Arte Digital'},
    'LAE': {mid: 'LAE', model: Models.Tec20, area: 'NEG', name: 'Lic. en Administración y Estrategia de Negocios'},
    'LAF': {mid: 'LAF', model: Models.Tec20, area: 'NEG', name: 'Lic. en Administración Financiera'},
    'LBC': {mid: 'LBC', model: Models.Tec20, area: 'SLD', name: 'Lic. en Biociencias'},
    'LCD': {mid: 'LCD', model: Models.Tec20, area: 'NEG', name: 'Lic. en Creación y Desarrollo de Empresas'},
    'LCM': {mid: 'LCM', model: Models.Tec20, area: 'COM', name: 'Lic. en Comunicación y Medios Digitales'},
    'LCP': {mid: 'LCP', model: Models.Tec20, area: 'NEG', name: 'Lic. en Contaduría Pública y Finanzas'},
    'LDF': {mid: 'LDF', model: Models.Tec20, area: 'CIS', name: 'Lic. en Derecho y Finanzas'},
    'LDI': {mid: 'LDI', model: Models.Tec20, area: 'ADI', name: 'Lic. en Diseño Industrial'},
    'LDN': {mid: 'LDN', model: Models.Tec20, area: 'NEG', name: 'Lic. en Innovación y Dirección de Negocios'},
    'LDP': {mid: 'LDP', model: Models.Tec20, area: 'CIS', name: 'Lic. en Derecho y Ciencia Política'},
    'LEC': {mid: 'LEC', model: Models.Tec20, area: 'CIS', name: 'Lic. en Economía'},
    'LED': {mid: 'LED', model: Models.Tec20, area: 'CIS', name: 'Lic. en Derecho'},
    'LEF': {mid: 'LEF', model: Models.Tec20, area: 'CIS', name: 'Lic. en Economía y Finanzas'},
    'LEM': {mid: 'LEM', model: Models.Tec20, area: 'COM', name: 'Lic. en Mercadotecnia'},
    'LIN': {mid: 'LIN', model: Models.Tec20, area: 'NEG', name: 'Lic. en Negocios Internacionales'},
    'LLE': {mid: 'LLE', model: Models.Tec20, area: 'COM', name: 'Lic. en Letras Hispánicas'},
    'LLN': {mid: 'LLN', model: Models.Tec20, area: 'NEG', name: 'Lic. en Logística Internacional'},
    'LMC': {mid: 'LMC', model: Models.Tec20, area: 'COM', name: 'Lic. en Mercadotecnia y Comunicación'},
    'LMI': {mid: 'LMI', model: Models.Tec20, area: 'COM', name: 'Lic. en Periodismo y Medios de Información'},
    'LNB': {mid: 'LNB', model: Models.Tec20, area: 'SLD', name: 'Lic. en Nutrición y Bienestar Integral'},
    'LP ': {mid: 'LP ', model: Models.Tec20, area: 'COM', name: 'Lic. en Psicología'},
    'LPL': {mid: 'LPL', model: Models.Tec20, area: 'CIS', name: 'Lic. en Ciencia Política'},
    'LPM': {mid: 'LPM', model: Models.Tec20, area: 'COM', name: 'Lic. en Publimidad y Comunicación de Mercados'},
    'LPO': {mid: 'LPO', model: Models.Tec20, area: 'NEG', name: 'Lic. en Psicología Organizacional'},
    'LPS': {mid: 'LPS', model: Models.Tec20, area: 'SLD', name: 'Lic. en Psicología Clínica y de la Salud'},
    'LRI': {mid: 'LRI', model: Models.Tec20, area: 'NEG', name: 'Lic. en Relaciones Internacionales'},
    'LTS': {mid: 'LTS', model: Models.Tec20, area: 'CIS', name: 'Lic. en Transformación Social'},
    'MC ': {mid: 'MC ', model: Models.Tec20, area: 'SLD', name: 'Médico Cirujano'},
    'MO ': {mid: 'MO ', model: Models.Tec20, area: 'SLD', name: 'Médico Cirujano Odontólogo'},
    'NEG': {mid: 'NEG', model: Models.Tec20, area: 'NEG', name: 'Negocios / Exploración'},
    'SLD': {mid: 'SLD', model: Models.Tec20, area: 'SLD', name: 'Salud / Exploración'},
    'TIE': {mid: 'TIE', model: Models.Tec20, area: 'TIE', name: 'Tecnologías de Información y Electrónica / Exploración'},
  },
  Tec21: {
    'AMC': {mid: 'AMC', model: Models.Tec21, area: 'AMC', name: 'Ambiente Construido / Exploración'},
    'ARQ': {mid: 'ARQ', model: Models.Tec21, area: 'AMC', name: 'Arquitecto'},
    'BGB': {mid: 'BGB', model: Models.Tec21, area: 'NEG', name: 'Lic. en Negocios Internacionales'},
    'CIS': {mid: 'CIS', model: Models.Tec21, area: 'CIS', name: 'Ciencias Sociales / Exploración'},
    'ESC': {mid: 'ESC', model: Models.Tec21, area: 'ESC', name: 'Estudios Creativos / Exploración'},
    'IAG': {mid: 'IAG', model: Models.Tec21, area: 'IBQ', name: 'Ing. en Biosistemas Agroalimentarios'},
    'IAL': {mid: 'IAL', model: Models.Tec21, area: 'IBQ', name: 'Ing. en Alimentos'},
    'IBQ': {mid: 'IBQ', model: Models.Tec21, area: 'IBQ', name: 'Ingeniería - Bioingeniería y Procesos Químicos (avenida) / Exploración'},
    'IBT': {mid: 'IBT', model: Models.Tec21, area: 'IBQ', name: 'Ing. en Biotecnología'},
    'IC ': {mid: 'IC ', model: Models.Tec21, area: 'AMC', name: 'Ing. Civil'},
    'ICI': {mid: 'ICI', model: Models.Tec21, area: 'ICI', name: 'Ingeniería - Ciencias Aplicadas (avenida) / Exploración'},
    'ICT': {mid: 'ICT', model: Models.Tec21, area: 'ICT', name: 'Ingeniería - Computación y Tecnologías de Información (avenida) / Exploración'},
    'IDM': {mid: 'IDM', model: Models.Tec21, area: 'ICI', name: 'Ing. en Ciencia de Datos y Matemáticas'},
    'IDS': {mid: 'IDS', model: Models.Tec21, area: 'IBQ', name: 'Ing. en Desarrollo Sustentable'},
    'IE ': {mid: 'IE ', model: Models.Tec21, area: 'IIT', name: 'Ing. en Electrónica'},
    'IFI': {mid: 'IFI', model: Models.Tec21, area: 'ICI', name: 'Ing. Físico Industrial'},
    'IID': {mid: 'IID', model: Models.Tec21, area: 'IIT', name: 'Ing. en Innovación y Desarrollo'},
    'IIS': {mid: 'IIS', model: Models.Tec21, area: 'IIT', name: 'Ing. Industrial y de Sistemas'},
    'IIT': {mid: 'IIT', model: Models.Tec21, area: 'IIT', name: 'Ingeniería - Innovación y Transformación (avenida) / Exploración'},
    'IM ': {mid: 'IM ', model: Models.Tec21, area: 'IIT', name: 'Ing. Mecánico'},
    'IMD': {mid: 'IMD', model: Models.Tec21, area: 'IIT', name: 'Ing. Biomédico'},
    'IMT': {mid: 'IMT', model: Models.Tec21, area: 'IIT', name: 'Ing. en Mecatrónica'},
    'INA': {mid: 'INA', model: Models.Tec21, area: 'ICI', name: 'Ing. en Nanotecnología'},
    'IQ ': {mid: 'IQ ', model: Models.Tec21, area: 'IBQ', name: 'Ing. Químico'},
    'IRS': {mid: 'IRS', model: Models.Tec21, area: 'ICT', name: 'Ing. en Robótica y Sistemas Digitales'},
    'ITC': {mid: 'ITC', model: Models.Tec21, area: 'ICT', name: 'Ing. en Tecnologías Computacionales'},
    'ITD': {mid: 'ITD', model: Models.Tec21, area: 'ICT', name: 'Ing. en Transformación Digital de Negocios'},
    'LAD': {mid: 'LAD', model: Models.Tec21, area: 'ESC', name: 'Lic. en Arte Digital'},
    'LAE': {mid: 'LAE', model: Models.Tec21, area: 'NEG', name: 'Lic. en Estrategia y Transformación de Negocios'},
    'LAF': {mid: 'LAF', model: Models.Tec21, area: 'NEG', name: 'Lic. en Finanzas'},
    'LBC': {mid: 'LBC', model: Models.Tec21, area: 'SLD', name: 'Lic. en Biociencias'},
    'LC ': {mid: 'LC ', model: Models.Tec21, area: 'ESC', name: 'Lic. en Comunicación'},
    'LCP': {mid: 'LCP', model: Models.Tec21, area: 'NEG', name: 'Lic. en Contaduría Pública y Finanzas'},
    'LDE': {mid: 'LDE', model: Models.Tec21, area: 'NEG', name: 'Lic. en Emprendimiento'},
    'LDI': {mid: 'LDI', model: Models.Tec21, area: 'ESC', name: 'Lic. en Diseño Industrial'},
    'LDO': {mid: 'LDO', model: Models.Tec21, area: 'NEG', name: 'Lic. en Desarrollo de Talento y Cultura Organizacional'},
    'LEC': {mid: 'LEC', model: Models.Tec21, area: 'CIS', name: 'Lic. en Economía'},
    'LED': {mid: 'LED', model: Models.Tec21, area: 'CIS', name: 'Lic. en Derecho'},
    'LEI': {mid: 'LEI', model: Models.Tec21, area: 'ESC', name: 'Lic. en Innovación Educativa'},
    'LEM': {mid: 'LEM', model: Models.Tec21, area: 'NEG', name: 'Lic. en Mercadotecnia'},
    'LIN': {mid: 'LIN', model: Models.Tec21, area: 'NEG', name: 'Lic. en Negocios Internacionales'},
    'LIT': {mid: 'LIT', model: Models.Tec21, area: 'NEG', name: 'Lic. en Inteligencia de Negocios'},
    'LLE': {mid: 'LLE', model: Models.Tec21, area: 'ESC', name: 'Lic. en Letras Hispánicas'},
    'LNB': {mid: 'LNB', model: Models.Tec21, area: 'SLD', name: 'Lic. en Nutrición y Bienestar Integral'},
    'LPE': {mid: 'LPE', model: Models.Tec21, area: 'ESC', name: 'Lic. en Periodismo'},
    'LPS': {mid: 'LPS', model: Models.Tec21, area: 'SLD', name: 'Lic. en Psicología Clínica y de la Salud'},
    'LRI': {mid: 'LRI', model: Models.Tec21, area: 'CIS', name: 'Lic. en Relaciones Internacionales'},
    'LTM': {mid: 'LTM', model: Models.Tec21, area: 'ESC', name: 'Lic. en Tecnologia y Produccion Musical'},
    'LTP': {mid: 'LTP', model: Models.Tec21, area: 'CIS', name: 'Lic. en Gobierno y Transformacion Publica'},
    'LUB': {mid: 'LUB', model: Models.Tec21, area: 'AMC', name: 'Lic. en Urbanismo'},
    'MC ': {mid: 'MC ', model: Models.Tec21, area: 'SLD', name: 'Medico Cirujano'},
    'MO ': {mid: 'MO ', model: Models.Tec21, area: 'SLD', name: 'Medico Cirujano Odontologo'},
    'NEG': {mid: 'NEG', model: Models.Tec21, area: 'NEG', name: 'Negocios / Exploración'},
    'SLD': {mid: 'SLD', model: Models.Tec21, area: 'SLD', name: 'Salud / Exploración'},
    'REG': {mid: 'REG', model: Models.Tec21, area: 'REG', name: 'Asociación Regional'},
    'CAP': {mid: 'CAP', model: Models.Tec21, area: 'CAP', name: 'Capítulo Estudiantil'},
    //'SOC': {mid: 'SOC', model: Models.Tec21, area: 'SOC', name: 'Sociedad de Alumnos'},
  },
};
